config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  root "books#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, counter_cache: true
  has_rich_text :description
  has_one_attached :cover do |attachable|
    attachable.variant :lazy_loaded, resize_to_limit: [10, 10]
  end


  after_save :touch_author

  scope :search, ->(search) { where("name ILIKE ?", "%#{search}%") if search.present? }

  cached_fields = %w[name description cover ]
  def touch_author
    # if attachment or rich_text_description changed, touch author
    author.touch if saved_changes.keys.any? { |k| k.in?(cached_fields) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @pagy, @authors = pagy(Author.all)
    console
  end

  def show
    @author = Author.includes(books: [{ cover_attachment: :blob }, :rich_text_description ]).find(params[:id])
  end

  def edit
  end

  def new
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @pagy, @books = pagy(Book.includes(:author).with_rich_text_description_and_embeds.with_attached_cover.search(params[:search]).order(:name))
    @search = params[:search]
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :status, :isbn, :description, :cover, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def form_classes
    "bg-sky-100 rounded-lg shadow-md p-6 border-0 px-4 py-4 w-full"
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/_author.html.erb
<div class="">
  <h3 class="text-xl font-bold">
    <%= link_to author.name, author_path(author), class: 'underline', data: {turbo: false} %>
  </h3>

  <p>
    <%= author.books_count %> books
  </p>
</div>

app/views/authors/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Authors#edit</h1>
  <p>Find me in app/views/authors/edit.html.erb</p>
</div>

app/views/authors/index.html.erb
<div class="">
  <h1 class="font-bold text-4xl">Authors</h1>

  <%= link_to "New author", new_author_path %>
  <div class="py-10">
    <%= turbo_frame_tag @authors do%>
      <%= render partial: 'author', collection: @authors %>
    <% end %>
  </div>
  
  <%== pagy_nav(@pagy,link_extra: 'data-turbo-action="advance"') if @pagy.pages > 1 %>

</div>

app/views/authors/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Authors#new</h1>
  <p>Find me in app/views/authors/new.html.erb</p>
</div>

app/views/authors/show.html.erb
<div>
  <h1 class="font-bold text-4xl"><%= @author.name %> sdadsa</h1>
  <p><%= @author.books_count %> books</p>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="book bg-gray-100 shadow-md rounded-md border border-slate-300 p-4 flex flex-col">
  <h3 class="bold text-xl"><%= book.name %></h3>
  <%= link_to book.author.name, author_path(book.author), class: 'text-sky-600 underline', "data-turbo": false %>


  <div class="py-5 blurred-img", style: "background-color: <%= url_for(book.cover.variant(:lazy_loaded))%>">
    
    <% if book.cover.attached? %>
      <%= image_tag book.cover, class: 'w-full h-auto max-h-[300px] object-cover shadow-md', width: 300, height: 300 %>
    <% end %>
    
  </div>
  <p class="my-5 prose"><%= book.description.to_plain_text.truncate(30) %></p>

  <p class="my-5">
    <%= link_to "Read more...", book, class: "px-4 py-2 bg-sky-600 text-gray-100 rounded-md", data: {turbo: "false"} %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: form_classes %>
  </div>

  <div class="">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: form_classes %>
  </div>

  <div class="my-10">
    <%= form.label :cover %>
    <%= form.file_field :cover %>

    
    <% if book.cover.persisted? %>
      <%= image_tag book.cover, class: 'w-64 h-64 object-cover', width:100, height: 100%>
    <% end %>
    
  </div>
  <div class="mb-4">
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status, class: form_classes %>
  </div>

  <div class="mb-4">
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn, class: form_classes %>
  </div>

  <div class="mb-4">
    <%= form.label :author_id, style: "display: block" %>
    <%= form.collection_select :author_id, Author.all, :id, :name, class: form_classes %>
  </div>

  <div class="mb-4">
    <%= form.submit "Save", class: 'bg-sky-600 px-4 py-2 rounded-md shadow-md text-sky-200 cursor-pointer' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Read more...", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<div class="">
  <h1 class="mb-10">Books</h1>

  <%= link_to "New book", new_book_path %>
</div>

<%= form_with url: books_path, method: :get do |f| %>
  <div class="py-5 flex flex-col justify-center items-center">
    <%= f.label :search, class: 'text-xl font-bold' %>
    <div class="w-full max-w-lg flex space-x-2 ">
      <div class="relative flex-1 justify-center items-center">
         <%= f.text_field :search, placeholder: "Search by name", class: 'w-full border-0 shadow-md rounded-md h-full', value: @search %>
          <%= f.submit "&times;".html_safe, class: "absolute top-1/2 right-0 transform -translate-x-1/2 -translate-y-1/2 fond-bold text-2xl pointer", type: "reset" %>
      </div>
      <%= f.submit "&#x1F50D;".html_safe, class: "bg-sky-600 hover:bg-sky-700  text-white font-bold py-2 px-4 rounded cursor-pointer h-full", type: "submit" %>
    
    </div>

    
  </div>
 
<% end %>

<div class="my-10 prose">
  <h3>Results for <%= params[:search] %></h3>
  <p>
    Showing
    <%= @books.size %>
    out of
    <%= @pagy.count %></p>
</div>


<%= turbo_frame_tag 'books' do %>
  <div id="books", class="grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3">
    <%= render partial: 'book', collection: @books, cached: true %>
  </div>
  <div class="flex justify-center items-center py-10">
    <%== pagy_nav(@pagy,link_extra: 'data-turbo-action="advance"') if @pagy.pages > 1 %>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="bg-slate-100 py-10 px-5 max-w-2xl mx-auto">

  <h1>New book</h1>

  <%= render "form", book: @book %>

  <br>

  <div>
    <%= link_to "Back to books", books_path %>
  </div>

</div>

app/views/books/show.html.erb
<div class="bg-gray-100 py-10 px-5">

  <h1 class="font-bold text-4xl"><%= @book.name %></h1>
  <p><%= @book.author.name %></p>
  
  <% if @book.cover.attached? %>
    <%= image_tag @book.cover, class: "w-64 h-64 rounded-md" %>
  <% end %>
  <p class="my-5 prose"><%= @book.description %></p>
  <div>
    <%= link_to "Edit this book", edit_book_path(@book) %> |
    <%= link_to "Back to books", books_path %>

    <%= button_to "Destroy this book", @book, method: :delete %>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAsync</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="">
      <nav class="navbar">
        <ul class="flex space-x-10">
          <li class="nav-link"><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </header>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>